//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANER()
        {
            this.BANER_D = new HashSet<BANER_D>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANER_D> BANER_D { get; set; }
    }
}
