//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INTEGRAEntities : DbContext
    {
        public INTEGRAEntities()
            : base("name=INTEGRAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANER> BANERs { get; set; }
        public virtual DbSet<BANER_D> BANER_D { get; set; }
        public virtual DbSet<CARRITO> CARRITOes { get; set; }
        public virtual DbSet<CARRITO_D> CARRITO_D { get; set; }
        public virtual DbSet<ESTADO> ESTADOes { get; set; }
        public virtual DbSet<LOCALIDAD> LOCALIDADs { get; set; }
        public virtual DbSet<MUNICIPIO> MUNICIPIOs { get; set; }
        public virtual DbSet<PAGO_T> PAGO_T { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOes { get; set; }
        public virtual DbSet<PRODUCTO_M> PRODUCTO_M { get; set; }
        public virtual DbSet<PRODUCTO_T> PRODUCTO_T { get; set; }
        public virtual DbSet<PRODUCTO_TIPO> PRODUCTO_TIPO { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<USUARIO_DIR> USUARIO_DIR { get; set; }
        public virtual DbSet<USUARIO_T> USUARIO_T { get; set; }
        public virtual DbSet<VENTA> VENTAs { get; set; }
        public virtual DbSet<VENTA_D> VENTA_D { get; set; }
    }
}
