//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTA()
        {
            this.VENTA_D = new HashSet<VENTA_D>();
        }
    
        public int ID { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> Entrega { get; set; }
        public Nullable<int> Direccion { get; set; }
        public Nullable<int> Metod_Pago { get; set; }
        public Nullable<bool> Factura { get; set; }
    
        public virtual PAGO_T PAGO_T { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual USUARIO_DIR USUARIO_DIR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA_D> VENTA_D { get; set; }
    }
}
